<?php
/**
 * See LICENSE.md for license details.
 */
/** @var Dhl\Ui\ViewModel\Order\Info\ShippingServices $viewModel */
$viewModel = $block->getData('viewModel');
$services = $viewModel->getSelectedServices();
?>
<?php if (count($services) > 0) : ?>
    <div class=" dhl-selected-services">
        <div class="section-title">
            <span class="title"><?= $block->escapeHtml(__('DHL Services')) ?></span>
        </div>
        <div class="section-content">
            <table class="order-information-table">
                <tbody>
                <?php foreach ($services as $service) : ?>
                    <tr>
                        <th><?= $block->escapeHtml($service['label']) ?></th>
                        <td><?= $block->escapeHtml($service['value']) ?></td>
                    </tr>
                <?php endforeach; ?>
                <?php if ($viewModel->getPickupLocationAddress()) : ?>
                <tr>
                    <th><?= $block->escapeHtml(__('Pickup Location')) ?></th>
                    <td>
                        <?php foreach ($viewModel->getPickupLocationAddress() as $addressLine) : ?>
                            <div><?= $block->escapeHtml($addressLine) ?></div>
                        <?php endforeach; ?>
                    </td>
                </tr>
                <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
<?php endif; ?>
