<?php
/**
 * See LICENSE.md for license details.
 */

/** @var \Dhl\ShippingCore\Model\RecipientStreet $recipientStreet */
$recipientStreet = $block->getData('recipient_street');
$orderId = $block->getData('order_id');
/** @var \Dhl\Ui\ViewModel\Order\Info\RecipientStreetView $viewModel */
$viewModel = $block->getData('viewModel');
?>
<?php if ($recipientStreet): ?>
    <section class="admin__page-section order-addresses">
        <div class="admin__page-section-content">
                <div class="admin__page-section-item order-shipping-address">
                    <?php /* Shipping Address */ ?>
                    <div class="admin__page-section-item-title">
                        <span class="title"><?= $block->escapeHtml(__('DHL Shipping Address')) ?></span>
                        <div class="actions"><?= $viewModel->getRecipientStreetEditLink($recipientStreet, $orderId); ?></div>
                    </div>
                    <strong><?= $block->escapeHtml(__('Street:')) ?></strong>
                    <span><?= $block->escapeHtml($recipientStreet->getName()) ?></span><br>
                    <strong><?= $block->escapeHtml(__('Number:')) ?></strong>
                    <span><?= $block->escapeHtml($recipientStreet->getNumber()) ?></span><br>
                    <strong><?= $block->escapeHtml(__('Supplement:')) ?></strong>
                    <span><?= $block->escapeHtml($recipientStreet->getSupplement()) ?></span>
                </div>
        </div>
    </section>
<?php endif; ?>
