<?php
/**
 * See LICENSE.md for license details.
 */
/** @var Dhl\Ui\ViewModel\Order\Info\ShippingServices $viewModel */
$viewModel = $block->getData('viewModel');
$services = $viewModel->getSelectedServices();
?>
<?php if (count($services) > 0): ?>
    <section class="admin__page-section dhl-selected-services">
        <div class="admin__page-section-title">
            <span class="title"><?= /* @escapeNotVerified */ __('DHL Services') ?></span>
        </div>
        <div class="admin__page-section-content">
            <table class="admin__table-secondary order-information-table">
                <tbody>
                    <?php foreach ($services as $service): ?>
                        <tr>
                            <th><?= $block->escapeHtml($service['label']) ?></th>
                            <td><?= $block->escapeHtml($service['value']) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </section>
<?php endif; ?>

