<?php
/**
 * See LICENSE.md for license details.
 */
declare(strict_types=1);
/** @var Dhl\Ui\ViewModel\Order\Packaging\Popup $viewModel */
$viewModel = $block->getPopupViewModel();
?>
<script type="text/x-magento-init">
    {
        "#packaging-content": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "dhl-packaging-popup": {
                        "component": "Dhl_Ui/js/packaging/controller",
                        "config": {
                            "items": <?= json_encode($viewModel->getItemData()) ?>,
                            "itemOptions": <?= json_encode($viewModel->getItemOptions()) ?>,
                            "packageOptions": <?= json_encode($viewModel->getPackageOptions()) ?>,
                            "serviceOptions": <?= json_encode($viewModel->getServiceOptions()) ?>
                        }
                    }
                }
            }
        }
    }

</script>
<div id="packaging-content" data-bind="scope: 'dhl-packaging-popup'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
