<?php
/**
 * See LICENSE.md for license details.
 */
declare(strict_types=1);

/** @var $block Magento\Shipping\Block\Adminhtml\Order\Packaging */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Dhl_Ui/js/packaging": {
                "name": "packaging-popup-modal",
                "target": "#packaging-window",
                "options": {
                    "title": "<?= __('Shipment Setup') ?>",
                    "type": "slide",
                    "buttons": []
                },
                "carrierCode": "<?= $block->escapeHtml(
                    $block->getShipment()->getOrder()->getShippingMethod(true)->getCarrierCode()
                ) ?>"
            }
        }
    }
</script>
<div id="packaging-window">
    <?= $block->getChildHtml() ?>
</div>
